name: sonify
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg
  - numpy<1.22  # TEMPORARY
  - obspy
  - pip
  - setuptools<58.4.0  # https://github.com/pypa/setuptools/issues/2497
  - pip:
    - --editable .
